# Generated by Django 4.2 on 2023-04-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
            ],
        ),
    ]
