# Generated by Django 4.2 on 2023-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_alter_job_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
