# Generated by Django 4.2 on 2023-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0003_job_is_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='تصویر لوگو'),
        ),
    ]
