# Generated by Django 4.2 on 2023-04-27 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0006_job_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('base_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('last_update', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_at'], 'verbose_name': 'شغل', 'verbose_name_plural': 'شغل ها'},
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='آدرس تصویر'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_last',
            field=models.BooleanField(default=False, verbose_name='آخرین آیتم'),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='لینک صفحه آگهی'),
        ),
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_module.site'),
            preserve_default=False,
        ),
    ]
