# Generated by Django 4.2 on 2023-06-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0009_jobseeker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=20, verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_module.site', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات اسکرپینگ',
                'verbose_name_plural': 'تنظیمات اسکرپینگ',
            },
        ),
    ]
